# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OM38aq617wONhEGJr3nc2SLoTxeBG27T
"""

from scapy.all import *

def traceroute(destination, max_hops):
    # Set the destination and maximum number of hops
    dport = 33434  # Destination port for traceroute
    ttl = 1

    while True:
        # Create an ICMP echo request packet with the specified TTL
        packet = IP(dst=destination, ttl=ttl) / ICMP()

        # Send the packet and receive a response
        reply = sr1(packet, verbose=False, timeout=1)

        if reply is None:
            # No response received, print an asterisk to indicate timeout
            print(f"{ttl}. *")
        elif reply.type == 3:
            # Destination reached, print the response IP address and break the loop
            print(f"{ttl}. {reply.src}")
            break
        else:
            # Intermediate hop reached, print the response IP address
            print(f"{ttl}. {reply.src}")

        # Increment the TTL for the next hop
        ttl += 1

        if ttl > max_hops:
            # Maximum number of hops reached, break the loop
            break

# Usage example
traceroute("www.example.com", 30)